version: '3'
services:
  app:
    image: golang:1.14
    container_name: hackine
    volumes:
    - ./:/app
    - ./cache/mod:/go/pkg/mod
    - ./cache/go-build:/root/.cache/go-build
    working_dir: /app
    ports:
    - "8080:80"
    command: [go, run, .]
